src/parser/class.js
test/parser/class.parser

Just added a minimal failing test to start with

fix const with an expression

---

package.json
test/functional/arrayTests.js

I've added a first set of mocha tests to the project to check the AST returned by the parser is what it should be.
These new tests only cover a very small portion of potential test cases and many more tests will be required to cover all of PHP's quirky edge-cases.
To run them, open a command line at the project root and run `mocha test/functional`

First set of mocha tests for the parser

---

src/lexer.js
src/parser.js

Added hard coded the required modules

---

src/index.js

Allow the default export for typescript

---

test/namespaceTest.js

https://github.com/glayzzle/php-parser/issues/139

WIP usegroup loc bug

---

src/parser/scalar.js
test/stringTests.js

Enhance AST representation of curlies / encapsed strings

---

package-lock.json
package.json
test/snapshot/__snapshots__/array.test.js.snap
test/snapshot/__snapshots__/ast.test.js.snap
test/snapshot/array.test.js
test/snapshot/ast.test.js

This shows a _very basic_ integration of jest-based snapshot testing. I hope it can be a starting point for future work in this direction. I wanted to share it early because unfortunately I don't have much free time to work on this right now.
```bash
npm run jest #run snapshot tests
npm run jest -- -u #update snapshots
```
refs #152

Jest-based snapshot testing (first steps)

---

src/parser/class.js
src/parser/expr.js
src/parser/scalar.js
test/snapshot/__snapshots__/acid.test.js.snap
test/snapshot/__snapshots__/location.test.js.snap
test/snapshot/location.test.js

Not all, but better.
fixes #204

fix: location

---

test/snapshot/__snapshots__/call.test.js.snap
test/snapshot/call.test.js

Just test to ensure all ok for future fixes

test: call

---

src/parser/variable.js
test/snapshot/__snapshots__/call.test.js.snap
test/snapshot/__snapshots__/graceful.test.js.snap
test/snapshot/__snapshots__/variable.test.js.snap
test/snapshot/call.test.js

partial https://github.com/glayzzle/php-parser/issues/185

[WIP] fix: respect `call` inside `staticlookup`

---

test/snapshot/__snapshots__/magic.test.js.snap
test/snapshot/magic.test.js

test: magic

---

test/snapshot/__snapshots__/break.test.js.snap
test/snapshot/__snapshots__/continue.test.js.snap
test/snapshot/break.test.js
test/snapshot/continue.test.js

test: continue and break node

---

src/parser/variable.js
test/snapshot/__snapshots__/bin.test.js.snap
test/snapshot/bin.test.js

partial #220, need fix for `static` too

fix: `instanceof`

---

src/ast.js
src/ast/encapsedpart.js
src/parser/scalar.js
test/snapshot/__snapshots__/acid.test.js.snap
test/snapshot/__snapshots__/ast.test.js.snap
test/snapshot/__snapshots__/encapsed.test.js.snap
test/snapshot/__snapshots__/location.test.js.snap
test/snapshot/__snapshots__/loop.test.js.snap
test/snapshot/__snapshots__/string.test.js.snap
test/snapshot/__snapshots__/variable.test.js.snap
test/snapshot/encapsed.test.js

fixes #175 
Now we can detect simple and complex syntax
It is very big enchantment :1st_place_medal:

feat: `EncapsedPart` node

---

test/snapshot/__snapshots__/encapsed.test.js.snap
test/snapshot/encapsed.test.js

fixes #192
Just test, we already fix this problem

test: issue 192

---

src/ast.js
src/ast/property.js
src/ast/propertystatement.js
src/parser/class.js
test/snapshot/__snapshots__/acid.test.js.snap
test/snapshot/__snapshots__/class.test.js.snap
test/snapshot/__snapshots__/comment.test.js.snap
test/snapshot/__snapshots__/namespace.test.js.snap
test/snapshot/__snapshots__/property.test.js.snap
test/snapshot/__snapshots__/propertystatement.test.js.snap
test/snapshot/property.test.js
test/snapshot/propertystatement.test.js

fix: use PropertyStatement node for multiple properties

---

src/ast.js
src/ast/useitem.js
src/parser/namespace.js
test/snapshot/__snapshots__/acid.test.js.snap
test/snapshot/__snapshots__/namespace.test.js.snap
test/snapshot/__snapshots__/usegroup.test.js.snap
test/snapshot/__snapshots__/useitem.test.js.snap
test/snapshot/usegroup.test.js
test/snapshot/useitem.test.js

feat: better ast for `useitem` node

---

src/ast.js
src/ast/traitalias.js
src/ast/traitprecedence.js
src/parser/class.js
test/snapshot/__snapshots__/acid.test.js.snap
test/snapshot/__snapshots__/class.test.js.snap
test/snapshot/__snapshots__/location.test.js.snap
test/snapshot/__snapshots__/traitprecedence.test.js.snap
test/snapshot/traitprecedence.test.js

feat: better ast for traituse and traitprecedence

---

src/parser/namespace.js
test/snapshot/__snapshots__/usegroup.test.js.snap
test/snapshot/usegroup.test.js

Allow leading backslash for use declaration inside use group, fixes #291

---

src/ast.js
src/parser/scalar.js
test/snapshot/__snapshots__/acid.test.js.snap
test/snapshot/__snapshots__/heredoc.test.js.snap
test/snapshot/__snapshots__/location.test.js.snap
test/snapshot/__snapshots__/nowdoc.test.js.snap
test/snapshot/__snapshots__/property.test.js.snap
test/snapshot/__snapshots__/string.test.js.snap
test/snapshot/heredoc.test.js
test/snapshot/nowdoc.test.js

- fix `raw` for `nowdoc` and `heredoc`
- tests

fix: heredoc and nowdoc

---

src/ast.js
src/ast/exit.js
src/parser/expr.js
test/snapshot/__snapshots__/acid.test.js.snap
test/snapshot/__snapshots__/ast.test.js.snap
test/snapshot/__snapshots__/exit.test.js.snap
test/snapshot/__snapshots__/expr.test.js.snap
test/snapshot/__snapshots__/location.test.js.snap
test/snapshot/array.test.js
test/snapshot/exit.test.js

The `status` property is misleading, based on spec (https://github.com/php/php-src/blob/php-7.4.0beta4/Zend/zend_language_parser.y#L1129) it is expression + tests

refactor: exit node

---

src/ast.js
src/parser/statement.js
test/snapshot/__snapshots__/acid.test.js.snap
test/snapshot/__snapshots__/goto.test.js.snap
test/snapshot/__snapshots__/label.test.js.snap
test/snapshot/__snapshots__/location.test.js.snap
test/snapshot/__snapshots__/statement.test.js.snap
test/snapshot/goto.test.js
test/snapshot/label.test.js
test/snapshot/location.test.js

Parser for php written on PHP do same, also it is allow to use better output comments

feat: use `identifier` for goto and label

---

test/snapshot/__snapshots__/byref.test.js.snap
test/snapshot/byref.test.js

Just test
As i said before we need add `byRef` property to `assign` node, it is good for prettier. Also php parser (written on PHP) also use `AssignRef` node

test: byRef

---

src/parser/variable.js
test/snapshot/__snapshots__/encapsed.test.js.snap
test/snapshot/encapsed.test.js

support:
```php
"$var[-1]";
```
https://github.com/php/php-src/blob/php-7.4.0beta4/Zend/zend_language_parser.y#L1282
also test other cases

fix: support negative offset in encapsed

---

src/parser/class.js
src/parser/expr.js
src/parser/statement.js
src/parser/utils.js
test/snapshot/__snapshots__/new.test.js.snap
test/snapshot/new.test.js

Just refactor and some tests
I find what using `read_*` and get name from https://github.com/php/php-src/blob/php-7.4.0beta4/Zend/zend_language_parser.y improve readability and navigation, and also improves the search for errors

refactor: extends and implements

---

src/parser/expr.js
test/snapshot/__snapshots__/isset.test.js.snap
test/snapshot/isset.test.js

Test + `read_*` for better reading and to simplify

refactor: isset variables

---

test.php
test/snapshot/__snapshots__/byref.test.js.snap
test/snapshot/byref.test.js

Just tests, we can close issue

test: issue-205

---

src/parser/variable.js
test/snapshot/__snapshots__/variable.test.js.snap
test/snapshot/variable.test.js

test: simple_variable

---

src/parser/expr.js
src/parser/function.js
src/parser/namespace.js
src/parser/variable.js

Just refactor names for better maintenance

Refactor read argument list

---

src/ast/assignref.js
src/lexer.js
src/lexer/strings.js
src/parser/class.js
src/parser/expr.js
src/parser/scalar.js
src/parser/statement.js
test/snapshot/__snapshots__/heredoc.test.js.snap
test/snapshot/__snapshots__/nowdoc.test.js.snap
test/snapshot/__snapshots__/string.test.js.snap
test/snapshot/heredoc.test.js
test/snapshot/nowdoc.test.js

This update one jest snapshot file, please check that. let me know if it needs some changes.

Add support for PHP RFC: Flexible Heredoc and Nowdoc Syntaxes

---

package-lock.json
src/lexer/numbers.js
src/lexer/property.js
src/lexer/scripting.js
src/lexer/utils.js
test/debug.js
test/snapshot/__snapshots__/number.test.js.snap
test/snapshot/number.test.js

implement https://wiki.php.net/rfc/numeric_literal_separator - related to https://github.com/glayzzle/php-parser/issues/346

Numeric literal separator

---

src/parser/expr.js
test/snapshot/__snapshots__/acid.test.js.snap
test/snapshot/__snapshots__/list.test.js.snap
test/snapshot/list.test.js

... instead of arrays.
Fixes #512

fix: parse nested shorthand lists as lists

---

src/ast/parameter.js
src/parser/function.js
test/snapshot/__snapshots__/acid.test.js.snap
test/snapshot/__snapshots__/arrowfunc.test.js.snap
test/snapshot/__snapshots__/byref.test.js.snap
test/snapshot/__snapshots__/class.test.js.snap
test/snapshot/__snapshots__/classreference.test.js.snap
test/snapshot/__snapshots__/closure.test.js.snap
test/snapshot/__snapshots__/comment.test.js.snap
test/snapshot/__snapshots__/function.test.js.snap
test/snapshot/__snapshots__/location.test.js.snap
test/snapshot/__snapshots__/parentreference.test.js.snap
test/snapshot/__snapshots__/php5.test.js.snap
test/snapshot/__snapshots__/php73.test.js.snap
test/snapshot/__snapshots__/scalar.test.js.snap
test/snapshot/__snapshots__/selfreference.test.js.snap
test/snapshot/__snapshots__/typereference.test.js.snap
test/snapshot/class.test.js

This patch is more inline with nikic PHP-Parser AST syntax, and should be 100% backward compatible with existing ast consumers.

feat(php8): promoted params v2

---

src/parser/function.js
test/snapshot/__snapshots__/function.test.js.snap
test/snapshot/function.test.js

This should fix: https://github.com/prettier/plugin-php/issues/1759

feat(PHP 8 danging comma): support dangling comma on function declaration

---

dist/php-parser.js
docs/Try.html
docs/ast.js.html
docs/ast_try.js.html
src/ast.js
src/ast/try.js
types.d.ts

- Fix "always"
- Allow null bodies on loops (e.g. `while (doSomething());`)
- Fix boolean typo

Typescript fixes

---

.eslintrc.js
package-lock.json
package.json

Preparing for a fresh release :rocket:

chore: update dependencies

---

.github/workflows/test.yml

seems that reproducibility in GH actions is not ideal ...

chore: increase benchmark threshold

---

src/ast.js
src/ast/variadicplaceholder.js
src/parser/function.js
test/snapshot/__snapshots__/function.test.js.snap
test/snapshot/function.test.js

Add PHP 8.1 first class callable support

---

src/lexer/numbers.js
src/lexer/utils.js
test/snapshot/__snapshots__/scalar.test.js.snap
test/snapshot/scalar.test.js

Implement parsing of PHP 8.1's explicit octals

---

src/parser/class.js
test/snapshot/__snapshots__/class.test.js.snap
test/snapshot/class.test.js

Handle property types using T_NAME_* tokens.

---

src/parser/expr.js
test/snapshot/__snapshots__/new.test.js.snap
test/snapshot/new.test.js

Add support for expressions in place of a class name in new statement.
Fixes: https://github.com/prettier/plugin-php/issues/2082

Fix for expression in new statement

---

src/lexer/attribute.js
test/snapshot/__snapshots__/attributes.test.js.snap
test/snapshot/attributes.test.js

Fixes https://github.com/glayzzle/php-parser/issues/1076

fix: add support for string concatenation in attributes

---

src/parser/class.js
src/parser/function.js

While working on a 8.3 typed constants PR I thought these might be updated.

A few unimportant code-style consistency changes
